# Copyright 2016 The WWU eLectures Team All rights reserved.
#
# Licensed under the Educational Community License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/ECL-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

mariadb:
  image: mariadb:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=opencast
    - MYSQL_USER=opencast
    - MYSQL_PASSWORD=opencast
  volumes:
    - ./assets/opencast-ddl.sql:/docker-entrypoint-initdb.d/opencast-ddl.sql:ro

activemq:
  image: webcenter/activemq:latest
  environment:
    - ACTIVEMQ_MIN_MEMORY=128
    - ACTIVEMQ_MAX_MEMORY=1024
    - ACTIVEMQ_ENABLED_SCHEDULER=true
    - ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT=true
    - ACTIVEMQ_ADMIN_LOGIN=admin
    - ACTIVEMQ_ADMIN_PASSWORD=password
    - ACTIVEMQ_WRITE_LOGIN=producer_login
    - ACTIVEMQ_WRITE_PASSWORD=producer_password
    - ACTIVEMQ_READ_LOGIN=consumer_login
    - ACTIVEMQ_READ_PASSWORD=consumer_password
    - ACTIVEMQ_JMX_LOGIN=jmx_login
    - ACTIVEMQ_JMX_PASSWORD=jmx_password
  volumes:
    - ./assets/activemq.xml:/opt/activemq/conf/activemq.xml:ro

opencast_admin:
  image: learnweb/opencast:admin
  environment:
    - ORG_OPENCASTPROJECT_SERVER_URL=http://opencast:8080
    - ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER=admin
    - ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS=opencast
    - ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER=opencast_system_account
    - ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS=CHANGE_ME
    - ORG_OPENCASTPROJECT_DB_VENDOR=MySQL
    - ORG_OPENCASTPROJECT_DB_JDBC_URL=jdbc:mysql://db/opencast
    - ORG_OPENCASTPROJECT_DB_JDBC_USER=opencast
    - ORG_OPENCASTPROJECT_DB_JDBC_PASS=opencast
    - PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL=http://opencast:8080
    - PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL=http://opencast:8081
    - ACTIVEMQ_BROKER_USERNAME=admin
    - ACTIVEMQ_BROKER_PASSWORD=password
    - ACTIVEMQ_BROKER_URL=tcp://activemq:61616
  links:
    - activemq:activemq
    - mariadb:db
  ports:
    - "8080:8080"
  volumes:
    - ./opencast-data:/data/opencast

opencast_presentation:
  image: learnweb/opencast:presentation
  environment:
    - ORG_OPENCASTPROJECT_SERVER_URL=http://opencast:8081
    - ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER=admin
    - ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS=opencast
    - ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER=opencast_system_account
    - ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS=CHANGE_ME
    - ORG_OPENCASTPROJECT_DB_VENDOR=MySQL
    - ORG_OPENCASTPROJECT_DB_JDBC_URL=jdbc:mysql://db/opencast
    - ORG_OPENCASTPROJECT_DB_JDBC_USER=opencast
    - ORG_OPENCASTPROJECT_DB_JDBC_PASS=opencast
    - PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL=http://opencast:8080
    - PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL=http://opencast:8081
    - ACTIVEMQ_BROKER_USERNAME=admin
    - ACTIVEMQ_BROKER_PASSWORD=password
    - ACTIVEMQ_BROKER_URL=tcp://activemq:61616
  links:
    - activemq:activemq
    - mariadb:db
  ports:
    - "8081:8080"
  volumes:
    - ./opencast-data:/data/opencast

opencast_worker:
  image: learnweb/opencast:worker
  environment:
    - ORG_OPENCASTPROJECT_SERVER_URL=http://opencast:8082
    - ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER=admin
    - ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS=opencast
    - ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER=opencast_system_account
    - ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS=CHANGE_ME
    - ORG_OPENCASTPROJECT_DB_VENDOR=MySQL
    - ORG_OPENCASTPROJECT_DB_JDBC_URL=jdbc:mysql://db/opencast
    - ORG_OPENCASTPROJECT_DB_JDBC_USER=opencast
    - ORG_OPENCASTPROJECT_DB_JDBC_PASS=opencast
    - PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL=http://opencast:8080
    - PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL=http://opencast:8081
    - ACTIVEMQ_BROKER_USERNAME=admin
    - ACTIVEMQ_BROKER_PASSWORD=password
    - ACTIVEMQ_BROKER_URL=tcp://activemq:61616
  links:
    - activemq:activemq
    - mariadb:db
  ports:
    - "8082:8080"
  volumes:
    - ./opencast-data:/data/opencast
