db:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=opencast
    - MYSQL_USER=opencast
    - MYSQL_PASSWORD=opencast
  ports:
    - "3306:3306"
  volumes:
    - ./assets/opencast-ddl.sql:/docker-entrypoint-initdb.d/:ro

activemq:
  image: webcenter/activemq:latest
  environment:
    - ACTIVEMQ_MIN_MEMORY=128
    - ACTIVEMQ_MAX_MEMORY=1024
    - ACTIVEMQ_ENABLED_SCHEDULER=true
    - ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT=true
    - ACTIVEMQ_ADMIN_LOGIN=admin
    - ACTIVEMQ_ADMIN_PASSWORD=password
    - ACTIVEMQ_WRITE_LOGIN=producer_login
    - ACTIVEMQ_WRITE_PASSWORD=producer_password
    - ACTIVEMQ_READ_LOGIN=consumer_login
    - ACTIVEMQ_READ_PASSWORD=consumer_password
    - ACTIVEMQ_JMX_LOGIN=jmx_login
    - ACTIVEMQ_JMX_PASSWORD=jmx_password
  volumes:
    - ./assets/activemq.xml:/opt/activemq/conf/activemq.xml:ro

opencast_admin:
  image: learnweb/opencast:admin
  environment:
    - ORG_OPENCASTPROJECT_SERVER_URL=http://dev:8080
    - ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER=admin
    - ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS=opencast
    - ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER=opencast_system_account
    - ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS=CHANGE_ME
    - ORG_OPENCASTPROJECT_DB_VENDOR=MySQL
    - ORG_OPENCASTPROJECT_DB_JDBC_URL=jdbc:mysql://db/opencast
    - ORG_OPENCASTPROJECT_DB_JDBC_USER=opencast
    - ORG_OPENCASTPROJECT_DB_JDBC_PASS=opencast
    - PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL=http://dev:8080
    - PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL=http://dev:8081
    - ACTIVEMQ_BROKER_USERNAME=admin
    - ACTIVEMQ_BROKER_PASSWORD=password
  links:
    - activemq:activemq
    - db:db
  ports:
    - "8080:8080"

opencast_presentation:
  image: learnweb/opencast:presentation
  environment:
    - ORG_OPENCASTPROJECT_SERVER_URL=http://dev:8081
    - ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER=admin
    - ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS=opencast
    - ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER=opencast_system_account
    - ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS=CHANGE_ME
    - ORG_OPENCASTPROJECT_DB_VENDOR=MySQL
    - ORG_OPENCASTPROJECT_DB_JDBC_URL=jdbc:mysql://db/opencast
    - ORG_OPENCASTPROJECT_DB_JDBC_USER=opencast
    - ORG_OPENCASTPROJECT_DB_JDBC_PASS=opencast
    - PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL=http://dev:8080
    - PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL=http://dev:8081
    - ACTIVEMQ_BROKER_USERNAME=admin
    - ACTIVEMQ_BROKER_PASSWORD=password
  links:
    - activemq:activemq
    - db:db
  ports:
    - "8081:8080"

opencast_worker:
  image: learnweb/opencast:worker
  environment:
    - ORG_OPENCASTPROJECT_SERVER_URL=http://dev:8082
    - ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER=admin
    - ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS=opencast
    - ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER=opencast_system_account
    - ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS=CHANGE_ME
    - ORG_OPENCASTPROJECT_DB_VENDOR=MySQL
    - ORG_OPENCASTPROJECT_DB_JDBC_URL=jdbc:mysql://db/opencast
    - ORG_OPENCASTPROJECT_DB_JDBC_USER=opencast
    - ORG_OPENCASTPROJECT_DB_JDBC_PASS=opencast
    - PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL=http://dev:8080
    - PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL=http://dev:8081
    - ACTIVEMQ_BROKER_USERNAME=admin
    - ACTIVEMQ_BROKER_PASSWORD=password
  links:
    - activemq:activemq
    - db:db
  ports:
    - "8082:8080"
